---
- name: "Install python-pip"
  package:
    pkg: "{{ install_python_pip_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "python-pip"
